# Generated by Django 5.2.7 on 2025-11-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_student_gender_remove_student_joined_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_app.student')),
            ],
        ),
    ]
