# Generated by Django 5.2.7 on 2025-11-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
